#define THIRDPARTYINFO_NAVER_APP_URL_SCHEME @"naverlogin"
#define THIRDPARTYINFO_NAVER_CONSUMER_KEY @"Q7D7lxUHQNJ3G9QXDvpT"
#define THIRDPARTYINFO_NAVER_CONSUMER_SECRET @"qt1RPqqLON"
#define THIRDPARTYINFO_NAVER_SERVICE_APP_NAME @"MoneyFlow"
